services:
  uat-db-v4:
    restart: unless-stopped
    image: bitnami/postgresql:11-debian-11
    container_name: uat-db-v4
    volumes:
      - uat_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5434:5432"

volumes:
  uat_data:
    name: uat-db-v4-new-up-new
    driver: local