services:
  strapi:
    container_name: strapi
    build: .
    image: michalvarys/uat-admin-v4:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      # - ./config:/opt/app/config
      # - ./src:/opt/app/src
      # - ./package.json:/opt/package.json
      # - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
      - proxy
      
  uat-db-v4:
    restart: unless-stopped
    image: bitnami/postgresql:11-debian-11
    container_name: uat-db-v4
    volumes:
      - uat_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5434:5432"

  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=sufursky@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    ports: 
      - 38080:80
      - 5050:5050
    networks:
      - proxy

volumes:
  uat_data:
    name: uat-db-v4-new-up-new
    driver: local
  
networks:
  proxy:
    external: true
  strapi:
    name: Strapi
    driver: bridge